### ISSUE TITLE
Push token not deliver to Customer.io

### ISSUE THREAD

**Issue by kot-ezhva** [customerio/customerio-reactnative#70] opened 2023-01-21 19:46 UTC
When I try to import FirebaseMessaging package in NotificationHandler.swift file, i got error  like `No such module 'FirebaseMessaging'`. Else use just 'Firebase' package, no errors, but push token not delivering, although it is in the function

Code NotificationHandler.swift: 
```
import Foundation
import CioMessagingPushFCM
import Firebase
import FirebaseMessaging

@objc
public class NotificationHandler : NSObject {

  public override init() {}

  // Register the app for push notifications
  // Skip this function if you don't want to request push permissions on launch
  @objc(registerPushNotification:)
  public func registerPushNotification(withNotificationDelegate notificationDelegate: UNUserNotificationCenterDelegate) {

    let center  = UNUserNotificationCenter.current()
    center.delegate = notificationDelegate
    center.requestAuthorization(options: [.sound, .alert, .badge]) { (granted, error) in
      if error == nil{
        DispatchQueue.main.async {
          UIApplication.shared.registerForRemoteNotifications()
        }
      }
    }
  }

  // Register device on receiving a device token (FCM)
  @objc(didReceiveRegistrationToken:fcmToken:)
  public func didReceiveRegistrationToken(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
    // NOTE!! Token exists here.
    MessagingPush.shared.messaging(messaging, didReceiveRegistrationToken: fcmToken)
    // ЧЯДНТ блт
  }

  // To capture push metrics
  @objc(userNotificationCenter:response:completionHandler:)
  public func userNotificationCenter(center:UNUserNotificationCenter, didReceive response: UNNotificationResponse, completionHandler: @escaping () -> Void){
    let _ = MessagingPush.shared.userNotificationCenter(center, didReceive: response, withCompletionHandler: completionHandler)
  }
}
```

AppDelegete.h
```
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import <UserNotifications/UserNotifications.h>
#import <FirebaseMessaging/FIRMessaging.h>
#import <UserNotifications/UserNotifications.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, UNUserNotificationCenterDelegate, FIRMessagingDelegate>

@property (nonatomic, strong) UIWindow *window;

@end
```

Injects in AppDelegate.m
```
...
NotificationHandler* pnHandlerObj = nil;
+ (void)initialize {
  pnHandlerObj = [[NotificationHandler alloc] init];
}
...
// FIREBASE
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
    
    // Set FCM messaging delegate
    [FIRMessaging messaging].delegate = self;
    // Register for remote push when the app starts
    [pnHandlerObj registerPushNotification:self];
  }
...
// Register for push notifications
[pnHandlerObj registerPushNotification:self];
...
- (void)messaging:(FIRMessaging *)messaging didReceiveRegistrationToken:(NSString *)fcmToken {
  [pnHandlerObj didReceiveRegistrationToken:messaging fcmToken: fcmToken];
}

// show push when the app is in foreground
 - (void)userNotificationCenter:(UNUserNotificationCenter* )center willPresentNotification:(UNNotification* )notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
   completionHandler( UNNotificationPresentationOptionAlert + UNNotificationPresentationOptionSound);
}
...
not worked too ⬇️ (Error: No visible @interface for 'NotificationHandler' declares the selector 'userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:')
// handle push when the user responds to the notification
// - (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler {
//  [pnHandlerObj userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
// }
```

Another functions (tracking, events etc) works good

thx)

**Comment by kot-ezhva** [comment] 2023-01-22 14:30
Also, fix it in documentation, pls
```
NotificationHandler* pnHandlerObj = nil;
+ (void)initialize {
  pnHandlerObj = [[NotificationHandler alloc] init];
}
```

**Comment by ami-aman** [comment] 2023-01-23 09:52
Hi @kot-ezhva 

Which version of `customerio-reactnative` are you using?

**Comment by kot-ezhva** [comment] 2023-01-23 11:26
> Hi @kot-ezhva
> 
> Which version of `customerio-reactnative` are you using?

Last, 2.0.0

**Comment by ami-aman** [comment] 2023-01-23 12:11
Thanks for your reply.

In v2 of our package, you are required to install Firebase dependencies manually. Make sure you have installed them using CocoaPods. You may refer [this](https://customer.io/docs/sdk/react-native/migrate-upgrade/#firebase-users-must-manually-install-firebase-dependencies) section of our docs.

Can you confirm if you have installed these libraries manually as mentioned in the docs ?

**Comment by kot-ezhva** [comment] 2023-01-23 12:15
> Thanks for your reply.
> 
> In v2 of our package, you are required to install Firebase dependencies manually. Make sure you have installed them using CocoaPods. You may refer [this](https://customer.io/docs/sdk/react-native/migrate-upgrade/#firebase-users-must-manually-install-firebase-dependencies) section of our docs.
> 
> Can you confirm if you have installed these libraries manually as mentioned in the docs ?

Yes, sure.
```
  pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
  pod 'Firebase'
  pod 'Firebase/Messaging'
```

**Comment by ami-aman** [comment] 2023-01-23 12:29
Thanks for confirming @kot-ezhva ! I appreciate it !

As I understand the issue, you are getting this error in one of your files `No such module 'FirebaseMessaging'` which is because you installed `Firebase/Messaging` and importing `FirebaseMessaging`. 

The correct way to import Firebase dependencies is

```
pod 'Firebase'
pod 'FirebaseMessaging'
```

Would you like to update the Podfile and check if you still get the error ? Again, I appreciate you responding swiftly.

**Comment by kot-ezhva** [comment] 2023-01-23 12:33
> Thanks for confirming @kot-ezhva ! I appreciate it !
> 
> As I understand the issue, you are getting this error in one of your files `No such module 'FirebaseMessaging'` which is because you installed `Firebase/Messaging` and importing `FirebaseMessaging`.
> 
> The correct way to import Firebase dependencies is
> 
> ```
> pod 'Firebase'
> pod 'FirebaseMessaging'
> ```
> 
> Would you like to update the Podfile and check if you still get the error ? Again, I appreciate you responding swiftly.

it's no difference, i tried any variants(

**Comment by ami-aman** [comment] 2023-01-24 09:32
Apologies that you are facing this issue. @kot-ezhva 

Would it be possible to share the Podfile with us ? If you are not comfortable sharing the details here then feel free to drop us an email on win@customer.io with the file and this ticket number.

**Comment by kot-ezhva** [comment] 2023-01-24 14:31
> Apologies that you are facing this issue. @kot-ezhva
> 
> Would it be possible to share the Podfile with us ? If you are not comfortable sharing the details here then feel free to drop us an email on [win@customer.io](mailto:win@customer.io) with the file and this ticket number.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.yoomoney.ru/scm/sdk/cocoa-pod-specs.git'
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

platform :ios, '13.0'

install! 'cocoapods', :disable_input_output_paths => true

# Mac M1 utility func from source
# https://github.com/facebook/react-native/blob/23717c6381a41b1c5f189376bfa5bc73c7a4da87/scripts/react_native_pods.rb#L182
def exclude_architectures(installer)
  projects = installer.aggregate_targets
    .map{ |t| t.user_project }
    .uniq{ |p| p.path }
    .push(installer.pods_project)

  arm_value = `/usr/sbin/sysctl -n hw.optional.arm64 2>&1`.to_i

  # Hermes does not support `i386` architecture
  excluded_archs_default = has_pod(installer, 'hermes-engine') ? "i386" : ""

  projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 " + excluded_archs_default
    end
    project.save()
  end
end

target 'CustomNameApp' do
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
  pod 'Firebase'
  pod 'Firebase/Messaging'
  #pod 'FirebaseMessaging'

  # YOOKASSA (ex Yandex Kassa)
  pod 'YooKassaPayments',
    :build_type => :dynamic_framework,
    :git => 'https://git.yoomoney.ru/scm/sdk/yookassa-payments-swift.git',
    :tag => '6.6.0'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'CustomNameAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    exclude_architectures(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

dynamic_frameworks = ['Storyly', 'SDWebImage']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if dynamic_frameworks.include?(pod.name)
      def pod.dynamic_framework?;
        true
      end
      def pod.build_type;
        Pod::BuildType.dynamic_framework
      end
    end
  end
end

target 'ImageNotification' do
  pod 'Firebase/Messaging'
end
```

**Comment by ami-aman** [comment] 2023-01-24 14:51
Thank you for sharing the podfile. Looking at it, seems like you are still trying to install `Firebase/Messaging`.

Can you try updating to the following 

 ```
pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
 pod 'Firebase'
 pod 'FirebaseMessaging'

```

and then run `pod install` in `ios` subfolder.

**Comment by kot-ezhva** [comment] 2023-01-24 14:52
> Thank you for sharing the podfile. Looking at it, seems like you are still trying to install `Firebase/Messaging`.
> 
> Can you try updating to the following
> 
> ```
> pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
> pod 'Firebase'
> pod 'FirebaseMessaging'
> ```
> 
> and then run `pod install` in `ios` subfolder.

https://github.com/customerio/customerio-reactnative/issues/70#issuecomment-1400270834

**Comment by ami-aman** [comment] 2023-01-24 14:54
Agreed, that you tried many variants but your current implementation looks different than what I suggested. I request you to give it a try !

**Comment by majlentes** [comment] 2023-01-25 09:28
I'm facing the same issue. My podfile looks like:


```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'
# Define find-and-replace function
def find_and_replace(dir, findstr, replacestr)
    Dir[dir].each do |name|
        text = File.read(name)
        replace = text.gsub(findstr,replacestr)
        replaced = text.index(replacestr)
        if replaced == nil && text != replace
            puts "Fix: " + name
            File.open(name, "w") { |file| file.puts replace }
            STDOUT.flush
        end
    end
    Dir[dir + '*/'].each(&method(:find_and_replace))
end

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'rn_new' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Pods for rn_new


  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'FBAudienceNetwork'
  pod 'react-native-survicate', :path => '../node_modules/@survicate/react-native-survicate'
  pod 'intercom-react-native', :path => '../node_modules/@intercom/intercom-react-native'
  pod 'RNRate', :path => '../node_modules/react-native-rate'
  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'
  pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
  pod 'Firebase'
  pod 'FirebaseMessaging'

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
    find_and_replace("Pods/RCT-Folly/folly/synchronization/DistributedMutex-inl.h",
                   "atomic_notify_one(state)", "folly::atomic_notify_one(state)")
  end

  post_integrate do |installer|
    project_path = "./rn_new.xcodeproj"
    project = Xcodeproj::Project.open(project_path)
    project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end
    project.save()
  end
end

target 'NotificationServiceExtension' do
  pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
end
```

**Comment by kot-ezhva** [comment] 2023-01-25 09:59
> Agreed, that you tried many variants but your current implementation looks different than what I suggested. I request you to give it a try !

Sure. I tried it first of all. Not worked, same errors

**Comment by ami-aman** [comment] 2023-01-25 13:42
Hi @kot-ezhva 
Thanks for your patience.

I tried reproducing the error using the code snippets and Podfile you provided and fortunately I was able to replicate it. I fixed the errors by following the steps mentioned below:

- Update Podfile.
```
  pod 'CustomerIO/MessagingPushFCM', '~> 2.0.4'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
```
Note that we added `:modular_headers => true` to support static libraries such as Firebase (alternately use `use_framework` but that might conflict with Flipper or any other library).
- Delete `Podfile.lock` (Do not worry, this will be auto-generated when you follow the next few steps below)
- Clear pods -  `rm -rf ios/Pods` (We will regenerate pods)
- Install pods - `cd ios && pod install && cd ..`
- Close Xcode and re launch once pods are re-installed
- `import FirebaseMessaging` in the respective file, if it is already there then you should not see the error now

I also deleted derived data before running the app to rule out the possibility of caching. 

I hope this fixes the error for you. Feel free to let me know if you still face any issue. I would be happy to help you further.

**Comment by ami-aman** [comment] 2023-01-25 13:44
Hey @majlentes

I see that you are also not using ` :modular_headers => true` for Firebase. Could you try the [above solution](https://github.com/customerio/customerio-reactnative/issues/70#issuecomment-1403639983) and let me know if that works for you.

**Comment by ami-aman** [comment] 2023-02-01 17:53
Hi @majlentes 

Thanks again for your patience. I wanted to update you that we have pushed version [2.0.1](https://github.com/customerio/customerio-reactnative/releases/tag/2.0.1) which includes an option to add device token directly from your app using `CustomerIO.registerDeviceToken(token)` where `token` expects a string value. Using that you will not need to make the above API call to register the device. 

[Here is the link](https://customer.io/docs/sdk/react-native/identify/#add-device) to the documentation !

Take a look and let us know if this unblocks you. Thank you !

**Comment by ami-aman** [comment] 2023-02-16 14:10
Closing this issue. Feel free to reopen, if required.

**Closed by ami-aman** 2023-02-16 14:10 UTC
