### ISSUE TITLE
Unable to listen to notification taps with expo-notifications after

### ISSUE THREAD

**Issue by dennisdelima21pe** [customerio/customerio-reactnative#241] opened 2024-02-23 13:34 UTC
SDK version:
"customerio-expo-plugin": "^1.0.0-beta.10"
"customerio-reactnative": "^3.3.0"

Describe the issue
When updating the expo sdk to the latest version, as well as updating expo-notification, the expo-notification functions Notifications.addNotificationResponseReceived or addNotificationReceivedListener do not work because there is a conflict or something with the customerio-expo-plugin and customerio - reactnative, I had to remove customerio-expo-plugin and customerio-reactnative from my project for them to work normally again, I'm waiting for a solution so I can add them back to my project.

Additional context
"expo-notifications": "^0.27.6",
"expo": "~50.0.6",

**Comment by mrehan27** [comment] 2024-02-23 14:40
Thank you for reaching out and sharing your experience. The behavior you're encountering is known and expected starting with version `3.4.0`. Can you please confirm the exact version you are using by checking your lock file?

From `3.4.0` onwards, callbacks for notifications sent from `Customer.io` are currently not supported, and the only available workaround involves using deep links. Callbacks from other SDKs should continue to function normally. For more detailed information, please refer to [this comment](https://github.com/customerio/customerio-reactnative/issues/239#issuecomment-1960808908).

I've internally added a +1 for the implementation of callbacks feature on your behalf. We will keep you updated with any future developments. Since this is duplicate of the linked issue, I'll close it for now. Please feel free to continue asking questions or share any further feedback you might have.

**Closed by mrehan27** 2024-02-23 14:40 UTC
