### ISSUE TITLE
List of crashes from xCode Organizer window connected to Customer io

### ISSUE THREAD

**Issue by beqramo** [customerio/customerio-reactnative#168] opened 2023-07-18 11:12 UTC
Hi,

I checked crashes on Xcode from production ios app and there are many connected to customer io.
I exported them maybe they can be helpful:
[wetransfer_dvxzad-be_roj0yuk1d74g-xccrashpoint_2023-07-18_1108.zip](https://github.com/customerio/customerio-reactnative/files/12079681/wetransfer_dvxzad-be_roj0yuk1d74g-xccrashpoint_2023-07-18_1108.zip)

To open them please use this link:
https://stackoverflow.com/questions/32900063/debugging-xccrashpoint
or this comment:
https://stackoverflow.com/a/75531524/8778814

Thanks

**Comment by levibostian** [comment] 2023-07-18 13:35
Thanks for reporting this, @beqramo. Sorry to hear that you have experienced some issues. 

While I review the logs, could you send me the version of the Customer.io SDK that you are using? Look in your `ios/Podfile.lock` file for lines that contain "CustomerIO". Send me those relevant lines. `cat ios/Podfile.lock | grep CustomerIO` will generate this list to send me if that's helpful.

**Comment by beqramo** [comment] 2023-07-18 13:37
3.0.0 was used in that version

**Comment by levibostian** [comment] 2023-07-18 13:53
3.0.0 of the React Native SDK, got it. 

Have you been able to reproduce this on your own in your app? Or, do you know what your app users are doing in your app to get to this crash? 

Was this crash occurring on older builds of your app? If not, what version of the SDK were you using in the last stable build of your app? 

Any information about the state your app is in would be very helpful. If you feel more comfortable, you can send us information to `win@customer.io` to continue the conversation there.

**Comment by beqramo** [comment] 2023-07-18 13:55
I really don't have any extra info as they were read and exported from xCode Organizer reports

**Comment by beqramo** [comment] 2023-07-18 16:11
Will come back on this, as I exported bugs from latest build

**Comment by beqramo** [comment] 2023-07-18 18:30
[CMMWwS6VC-GarX8--k4-CK 2.xccrashpoint.zip](https://github.com/customerio/customerio-reactnative/files/12087990/CMMWwS6VC-GarX8--k4-CK.2.xccrashpoint.zip)
[BsynWwLo5wL38JfZ8PbbmS.xccrashpoint.zip](https://github.com/customerio/customerio-reactnative/files/12087993/BsynWwLo5wL38JfZ8PbbmS.xccrashpoint.zip)
[B-Mt-ImuWKvPw6TxmXjscq.xccrashpoint.zip](https://github.com/customerio/customerio-reactnative/files/12087997/B-Mt-ImuWKvPw6TxmXjscq.xccrashpoint.zip)
[CUI3RT1y7gVkeQebMSCEV6 2.xccrashpoint.zip](https://github.com/customerio/customerio-reactnative/files/12087998/CUI3RT1y7gVkeQebMSCEV6.2.xccrashpoint.zip)
[uYBuE-9lZMmVekXjcQyxh 2.xccrashpoint.zip](https://github.com/customerio/customerio-reactnative/files/12088003/uYBuE-9lZMmVekXjcQyxh.2.xccrashpoint.zip)


I put some of the errors here(Indeed there are more) from the previous version of the app that was working on 2.5.1 of the library.

Some of them are still the same as what I noticed.

If you want more info or you want to take a look at the Xcode crash report let's get in touch and will find some time for it.

Thanks

**Comment by levibostian** [comment] 2023-07-18 19:59
Thanks again for sending this report to us. 

Based on the stacktraces you provided, we came up with a fix to address this issue. We are internally testing this fix and will ship it to production after testing is complete. 

I will send you an update here when we have shipped the fix. It would be great if you could install the update and report back if the issue continues.

**Comment by levibostian** [comment] 2023-07-20 19:09
We have released version 3.1.4 of the React Native SDK that addresses these crashes. We recommend updating to this version and reporting stacktraces to us if you experience them again. 

*Note:*: Be sure to run `pod update --repo-update --project-directory=ios` after `npm install` of installing the `3.1.4` release. You know that the update was successful if you see `CustomerIOTracking = 2.7.5` in your `ios/Podfile.lock` file. Indicating the native SDK version has been upgraded.

**Comment by levibostian** [comment] 2023-07-20 19:11
I'll close this issue since the issue has been addressed. Happy to reopen it if the issue still occurs.

**Comment by levibostian** [comment] 2023-07-24 13:41
Version `3.1.4` of the React Native SDK contained a bug fix that addressed this issue. We were able to reproduce the crash and fixed it with the bug fix. 

We discovered that React Native apps using `3.1.4` that is initializing the SDK twice in their app (once in `App.js` and once in `AppDelegate`) could 
Through further testing, we discovered an edge case

**Comment by beqramo** [comment] 2023-07-28 16:08
Hi @levibostian,
No update on this? as we are going to release a new app and I don't want even with an old one because of above bugs.

**Comment by beqramo** [comment] 2023-07-31 15:18
Okay thank you. will remove it for now as I prefer no crashes than that stats.

**Comment by beqramo** [comment] 2023-08-29 17:34
@levibostian any update on this?

**Comment by levibostian** [comment] 2023-08-29 18:03
Thanks for asking, @beqramo. 

Unfortunately, I cannot share details on when to expect a fix to be shipped. This issue remains to be a priority for us. 

We'll keep you updated on our progress. Thanks again for sharing this important issue and all of the details for it.

**Comment by beqramo** [comment] 2023-10-25 16:15
@levibostian any update?

**Comment by levibostian** [comment] 2023-10-26 17:58
We greatly appreciate your patience here, @beqramo. 

Our team has continued to work on addressing this issue although I can understand that it has taken longer then originally expected. 

As before, I cannot share details on when to expect a fix to be shipped. If I get an update on that I will share it in this issue. 

Thanks again for the patience and the help on this.

**Comment by levibostian** [comment] 2023-11-07 20:14
Sorry to cause confusion by closing this issue. 

It has been addressed in the iOS SDK version 2.9.2. React Native SDK release is planned to be released soon.

**Comment by levibostian** [comment] 2023-11-08 14:42
@beqramo, React Native SDK version 3.3.1 has been released which addresses this issue. 

Thank you again for reporting this to us and working with us to get it released. We appreciate it!

**Closed by levibostian** 2023-11-08 14:42 UTC

**Comment by beqramo** [comment] 2023-11-08 16:22
Thanks.
