### ISSUE TITLE
Device not tracked on Production build when enableInApp is enabled

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-reactnative#131] opened 2023-05-05 11:39 UTC
**SDK version:** 
2.3.3 with expo plugin 1.0.0-beta.7

**Are logs available?** 
none

**Describe the issue**
I'm trying to get the sdk work in my project. 
Initialize() and identify() do work OK (I have events in Activity tab attributed to `Customer.io Expo Client/1.0.0-beta.7`), but I have issues with Push Notifications on an iOS Production build that do not exist in iOS Simulator.

While working with the simulator, I successfully have a device associated with my user (arm64), but when working with a real device and a production build, I cannot get any device to be associated.
One difference I'm aware of is that simulator does Grant Push permission by default. I use `showPromptForPushNotifications`to request permission, and my logs show that the response is indeed 'Granted' for the real device as well. So it should work.
I also tried to identify() again after permission has been granted. But no luck.

Any idea ?

**Comment by mrehan27** [comment] 2023-05-05 13:04
Hi @jbtheard. Can you please try running non-production build on the same device and see if that device is identified or not?

**Comment by jbtheard** [comment] 2023-05-05 14:12
What do you mean by non production build ?

What I meant by “production” is actually a “pre-production” build for internal testing, that is, in our experience, very similar to a Store distribution.

See expo doc about “internal” distribution <https://github.com/customerio/customerio-reactnative/issues/131>.

The only difference in our simulator is that it’s what they call a “devClient” build <https://docs.expo.dev/build-reference/eas-json/#developmentclient>

**Comment by mrehan27** [comment] 2023-05-09 07:07
@jbtheard If your pre-production build has logs enabled, that will work as well. We just need to monitor logs.

Can you please enable logs in it and share it with us here or email at win@customer.io and add reference to this issue so we can take a look and identify what could be breaking this?

**Comment by jbtheard** [comment] 2023-05-09 11:40
Please have a look at my comment [here](https://github.com/customerio/customerio-reactnative/issues/128#issuecomment-1540001589) where I explain I don't know how to do that. It's actually the first time in my dev experience with react Native that I need to look at native level logs that aren't reported at JS level. Would appreciate if you could guide me into this.

**Comment by jbtheard** [comment] 2023-05-11 10:15
> No issues @jbtheard. I have [replied to the issue](https://github.com/customerio/customerio-reactnative/issues/128#issuecomment-1541637680). Let us know if you have more question on it. Once you are able to capture the logs, please share them with us here or at win@customer.io so we can look into this further.

Logs sent to win@customer.io !

**Comment by Shahroz16** [comment] 2023-05-11 10:56
Thanks @jbtheard, we will review them. Can you confirm one small thing for me, have you tried it with a fresh install on the production build? I want to narrow it down if device is not tracked in both cases when app is freshly installed vs running app,

**Comment by jbtheard** [comment] 2023-05-12 10:41
So, based on your suggestion I have done a log for a fresh install, and indeed some things are worth noting:

with `enableInApp=false` I do have a device registered and I get the following logs:

```
debug	09:18:45.471909+0100	MindDay	(siteid:8fb54) deleting expired tasks from the queue
[...]
debug	09:18:45.589009+0100	MindDay	(siteid:8fb54) storing device token to device storage b81894624f40aee1a40f2bb745a1d200f0531463eb00aeb1fbc59d7db751fae7
debug	09:20:01.004210+0100	MindDay	(siteid:8fb54) identify profile attributes none
debug	09:20:01.004296+0100	MindDay	(siteid:8fb54) added queue task data {"identifier":"user_2PgXGJ8fvAcRBDG0CKJAiPYGLtD"}
[]
debug	09:20:01.009262+0100	MindDay	(siteid:8fb54) storing identifier on device storage user_2PgXGJ8fvAcRBDG0CKJAiPYGLtD
debug	09:20:01.010164+0100	MindDay	(siteid:8fb54) registering existing device token to newly identified profile: user_2PgXGJ8fvAcRBDG0CKJAiPYGLtD
debug	09:20:01.010231+0100	MindDay	(siteid:8fb54) storing device token to device storage b81894624f40aee1a40f2bb745a1d200f0531463eb00aeb1fbc59d7db751fae7
debug	09:20:01.010566+0100	MindDay	(siteid:8fb54) running hooks profile identified user_2PgXGJ8fvAcRBDG0CKJAiPYGLtD
debug	09:20:01.013425+0100	MindDay	(siteid:8fb54) added queue task data {"attributes_json_string":"{\"device\":{\"attributes\":{\"app_version\":\"1.4.7\",\"cio_sdk_version\":\"1.0.0-beta.8\",\"device_locale\":\"en-GB\",\"device_manufacturer\":\"Apple\",\"device_model\":\"iPhone14,4\",\"device_os\":\"16.4.1\",\"push_enabled\":\"true\"},\"id\":\"b81894624f40aee1a40f2bb745a1d200f0531463eb00aeb1fbc59d7db751fae7\",\"last_used\":1683879601,\"platform\":\"iOS\"}}","profile_identifier":"user_2PgXGJ8fvAcRBDG0CKJAiPYGLtD"}
```

When I set `enableInApp=true` I get the following logs:

```
debug	11:39:08.807338+0100	MindDay	(siteid:8fb54) deleting expired tasks from the queue
debug	11:39:08.822228+0100	MindDay	(siteid:8fb54) deleting tasks older then 2023-05-09T11:39:08+0100,
current time is: 2023-05-12T11:39:08+0100
debug	11:39:08.823183+0100	MindDay	(siteid:8fb54) Setting up in-app module...
debug	11:39:08.838161+0100	MindDay	(siteid:8fb54) deleting 0 tasks. 
 Tasks: []
debug	11:40:15.034758+0100	MindDay	(siteid:8fb54) identify profile attributes none
debug	11:40:15.034987+0100	MindDay	(siteid:8fb54) added queue task data {"identifier":"user_2PgoJfjv8HY3QzYMxiVFSEtbeiM"}
debug	11:40:15.038470+0100	MindDay	(siteid:8fb54) processing queue status QueueStatus(queueId: "8fb54b1e742471ac8e16", numTasksInQueue: 1).
debug	11:40:15.038502+0100	MindDay	(siteid:8fb54) Timer (mbczvqakfk) making a timer for 30.0 seconds.
debug	11:40:15.038552+0100	MindDay	(siteid:8fb54) storing identifier on device storage user_2PgoJfjv8HY3QzYMxiVFSEtbeiM
debug	11:40:15.040600+0100	MindDay	(siteid:8fb54) running hooks profile identified user_2PgoJfjv8HY3QzYMxiVFSEtbeiM
debug	11:40:15.041090+0100	MindDay	(siteid:8fb54) registering profile user_2PgoJfjv8HY3QzYMxiVFSEtbeiM for in-app
debug	11:40:15.755717+0100	MindDay	(siteid:8fb54) track screen view event attributes {"data":{},"name":"OnboardingDailyReminder","timestamp":1683888015,"type":"screen"}
debug	11:40:15.755764+0100	MindDay	(siteid:8fb54) added queue task data {"attributes_json_string":"{\"data\":{},\"name\":\"OnboardingDailyReminder\",\"timestamp\":1683888015,\"type\":\"screen\"}","identifier":"user_2PgoJfjv8HY3QzYMxiVFSEtbeiM"}
debug	11:40:15.761472+0100	MindDay	(siteid:8fb54) processing queue status QueueStatus(queueId: "8fb54b1e742471ac8e16", numTasksInQueue: 2).
debug	11:40:15.761504+0100	MindDay	(siteid:8fb54) Timer (mbczvqakfk) already scheduled to run. Skipping request.
debug	11:40:15.761884+0100	MindDay	(siteid:8fb54) setting route for in-app to OnboardingDailyReminder
debug	11:40:15.803126+0100	MindDay	(siteid:8fb54) identify profile attributes none
debug	11:40:15.804105+0100	MindDay	(siteid:8fb54) added queue task data {"identifier":"user_2PgoJfjv8HY3QzYMxiVFSEtbeiM"}
debug	11:40:15.807060+0100	MindDay	(siteid:8fb54) processing queue status QueueStatus(queueId: "8fb54b1e742471ac8e16", numTasksInQueue: 3).
```
...which result in device not being reported to your system. so I assume that's where the true issue is!

**Comment by jbtheard** [comment] 2023-05-16 09:40
Actually I tried again this morning and even with in-app disabled it does fail :(
Any suggestion ?

**Comment by mrehan27** [comment] 2023-05-16 11:04
Hey @jbtheard. Sorry to hear this. Can you please confirm which version of react native SDK are you using? If you are using an older version, can you please try updating [react native to `2.3.3`](https://github.com/customerio/customerio-reactnative/releases) and [iOS SDK to `2.5.1`](https://github.com/customerio/customerio-ios/releases)?

**Comment by jbtheard** [comment] 2023-05-16 11:32
As mentionnés in first post, 2.3.3

**Comment by mrehan27** [comment] 2023-05-16 12:05
@jbtheard Can you please confirm if latest iOS SDK is being used as well? Sorry for asking this again. But we recently [fixed a bug in iOS for device token](https://github.com/customerio/customerio-ios/releases/tag/2.5.1) so I just to make sure if your app is fetching the latest iOS SDK.

If you are using react native or expo bare workflow, you can run the following
```
pod update --repo-update --project-directory=ios
```

If you are using expo managed workflow, you can use `prebuild` or `prebuild --clean` to update the SDK

**Comment by jbtheard** [comment] 2023-05-17 08:51
Hi,
For the context, I'm using expo managed workflow. Note that because I'm using EAS to build, and because I'm not editing any file after `prebuild`, I don't see the need to execute `prebuild` and I let EAS pick his own pod version. 
From the EAS logs, it seems to be 2.5.1
```
Installing CustomerIO (2.5.1)
Installing CustomerIOCommon (2.5.1)
Installing CustomerIOMessagingInApp (2.5.1)
Installing CustomerIOMessagingPush (2.5.1)
Installing CustomerIOMessagingPushAPN (2.5.1)
Installing CustomerIOTracking (2.5.1)
```

**Comment by mrehan27** [comment] 2023-05-17 10:08
This looks fine to me. Can you please share your [plugin configuration file](https://customer.io/docs/sdk/expo/getting-started/#configure-the-plugin) after replacing your keys with dummy values here or at win@customer.io so we can take a look into it and try reproducing it at our end?

**Comment by jbtheard** [comment] 2023-05-17 11:07
So, I feel dumb as I actually realised that I had mismatch in my keys between the one loaded by iOS at build time (presumably) and the one used by the JS initialisation.

With both keys matching it seems to work ok.

I would suggest we could use a single source of truth for secrets like that rather than potentially using different sources.

At least it seems you can now close this issue. Sorry about that!

**Comment by mrehan27** [comment] 2023-05-17 11:35
Thanks for the updates @jbtheard. We are aware of the challenges for having multiple sources for keys and is in our roadmap. I've added a +1 to internal ticket on your behalf so we can update you whenever the changes are available. Since the issue in discussion is resolved, I'm closing this ticket for now. Please feel free to re-open if you encounter the issue again.

**Closed by mrehan27** 2023-05-17 11:35 UTC
