### ISSUE TITLE
Receive push notification with images

### ISSUE THREAD

**Issue by edersonfaccin** [customerio/customerio-reactnative#209] opened 2023-10-19 13:58 UTC
SDK version: 3.1.8

How can i receive rich push notifications with images in my app with react native?
In CustomerIO dashboard i put an image in my payload, but in my app i receive push notification without my image, this image is a public url.

Someone did this feature already? 

I am using iphone simulator and real device.

**Comment by levibostian** [comment] 2023-10-19 14:25
Hey there, @edersonfaccin. 

Have you followed all of the [instructions for setting up push notifications using the React Native SDK](https://customer.io/docs/sdk/react-native/push-notifications/push/)? After you follow all of those instructions, you should be able to see an image on your push on your device. 

I do want to note that, yes, this feature is supported by the SDK. Our team would be happy to help you here on GitHub if you wish, but you may receive a faster response for this type of question by emailing technical support at `win@customer.io`.

**Comment by edersonfaccin** [comment] 2023-10-19 18:33
Hi @levibostian, thanks for this awnser, i followed this docs steps but without success, after i updated ios/Podfile the build crash.

Do you have some example?

i am using react-native 0.71.11, with customerio-reactnative 3.1.13.

**Comment by lj-cio** [comment] 2023-10-20 18:57
Hi @edersonfaccin, jumping in for Levi here to see if our sample apps [here](https://github.com/customerio/customerio-reactnative/tree/main/Apps) can be helpful.  There are two examples available, one using APN and one using FCM as the push service.  

For missing images, the most common reason is that the NSE target isn't added or configured correctly.  For this and other potential causes, we have a few [Troubleshooting steps here](https://customer.io/docs/sdk/react-native/updates-and-troubleshooting/troubleshooting/#check-that-you-embedded-nse) that could help point you in the right direction.

**Comment by edersonfaccin** [comment] 2023-10-24 14:26
Hi @lj-cio i follow the steps and i checked and follow the example project that you had sent to me, and in build show to me the problem in the end of the build.

![Screenshot 2023-10-24 at 11 16 42](https://github.com/customerio/customerio-reactnative/assets/42881030/1c5c5166-fafd-481d-ab1a-dd1c6b306bf7)

i searched on internet and no solution for this.

Any steps more to check?

**Comment by levibostian** [comment] 2023-10-24 15:54
I am not 100% sure what the issue is from your screenshot. This issue might be resolved by cleaning your project's build folders. Therefore, I suggest deleting the `ios/Pods` directory and running your command again. 

Also, it would be helpful to see your `ios/Podfile`. You can send it to `win@customer.io` if you're not comfortable sharing it publicly here.

**Comment by edersonfaccin** [comment] 2023-10-24 16:14
i just to send podfile to win@customer.io

thanks.

**Closed** 2023-11-24 19:47 UTC
