### ISSUE TITLE
Android icon for push notification

### ISSUE THREAD

**Issue by thozh** [customerio/customerio-reactnative#321] opened 2024-09-12 09:16 UTC
**SDK version:**  3.8.0 and ^1.0.0-beta.15 for expo plugin

**Describe the bug**
The Android notification icon for our app is not displaying correctly. Instead of showing our app's icon, it's displaying nothing in the status bar and notification drawer.

**Comment by mrehan27** [comment] 2024-09-12 11:34
Hey @thozh. Thanks for reaching out and sharing this. This issue looks very similar to https://github.com/customerio/customerio-expo-plugin/issues/115 reported earlier in Expo plugin. Unfortunately, we haven't made any changes to the plugin yet. So the workaround [suggested here](https://github.com/customerio/customerio-expo-plugin/issues/115#issuecomment-1823966270) remains the only option. I'll also +1 internal ticket on your behalf.

Closing this as we already have an issue open for the change. We'll keep you posted on any future improvements. Even though the issue is closed, please feel free to ask any questions you may still have. Have a great day!

**Closed by mrehan27** 2024-09-12 11:34 UTC
