### ISSUE TITLE
iOS Build failed with: Undefined symbol: os.Logger.init

### ISSUE THREAD

**Issue by nickfla1-mxm** [customerio/customerio-reactnative#25] opened 2022-09-12 10:14 UTC
Error log
```
Undefined symbols for architecture x86_64:
  "os.Logger.init(subsystem: Swift.String, category: Swift.String) -> os.Logger", referenced from:
      Common.ConsoleLogger.(printMessage in _2BB8370657B49B0C392BA980561C45D4)(Swift.String, __C.os_log_type_t) -> () in libCustomerIOCommon.a(Log.o)
  "type metadata accessor for os.Logger", referenced from:
      Common.ConsoleLogger.(printMessage in _2BB8370657B49B0C392BA980561C45D4)(Swift.String, __C.os_log_type_t) -> () in libCustomerIOCommon.a(Log.o)
  "os.Logger.logObject.getter : __C.OS_os_log", referenced from:
      Common.ConsoleLogger.(printMessage in _2BB8370657B49B0C392BA980561C45D4)(Swift.String, __C.os_log_type_t) -> () in libCustomerIOCommon.a(Log.o)
ld: symbol(s) not found for architecture x86_64
```

Tested on macOS Monterey 12.4, with:
- XCode 13.2
- XCode 13.4
- XCode 14 Beta 6

Used Podfile:
```rb
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'Playground' do
  use_unimodules!({modules_paths: ['../../../node_modules']})
  config = use_native_modules!

  use_react_native!(
      :path => config["reactNativePath"],
      :hermes_enabled => true
  )

  # Customer.io Firebase Cloud Messaging sdk
  pod 'CustomerIO/MessagingPushFCM', '~> 1.2.0-alpha.3'
  pod 'FirebaseMessaging', :modular_headers => true

  use_flipper!({ 'Flipper' => '0.140.0', 'Flipper-Folly' => '2.6.10' })
  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

**Comment by ami-aman** [comment] 2022-09-13 15:33
Hey @nickfla1-mxm 
Thanks for bringing this to our attention. It is very possible that this could be because of the cached files/data. 

As a suggestion, can you try doing the following 
- Deleting the derived data, clean the build folder and restart XCode
- Clean yarn cache using `yarn cache clean`
- Removing node_modules folder `rm -rf node_modules && rm -rf ios/Pods`
- Re-installing libraries `yarn install`
- Go to your ios subfolder and run `pod install`

Let us know if this works for you.

**Comment by jparratt-pogo** [comment] 2022-09-15 22:43
Hello @ami-aman , I have experienced the same issue and was able to work around it by commenting out the following block in `Log.swift` inside of `CustomerIOCommon`, specifically everything inside the availability check: 
![image](https://user-images.githubusercontent.com/92383083/190519374-3025a131-a697-4b2f-b407-d108e348219e.png)

I have followed your steps above but they do not seem to resolve the issue, I have also attempted to update the deployment targets for both my application as well as the individual pods to 14.0 and I still see the same errors.
Monterey 12.5.1
XCode 14.0

Please let me know if there is any other information I can provide to help, thanks.

**Comment by ami-aman** [comment] 2022-09-16 10:19
Hi @jparratt-pogo 
Thanks for sharing the detail and the workaround to solve the issue. 

I have documented the issue internally and either myself or someone from our team will investigate the issue and get back to you with a solution very soon.

**Comment by ami-aman** [comment] 2022-09-30 08:50
Closing this issue for now. We'll notify when this issue is fixed !

**Comment by ami-aman** [comment] 2022-10-13 10:02
Hi @nickfla1-mxm @jparratt-pogo 

Our team was able to spend some time on this issue and found that the error is caused by incompatible build settings and occurs even when the SDK is removed and the os.Logger added on its own.

**To Fix**

- Go to project target and open Build Settings
- Search for LIBRARY_SEARCH_PATH
- Remove `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`
The linker searches for the libraries on these path. iOS 14 requires swift version higher than 5, hence it fails to locate libraries such as this Logger when the path is pinned to 5.

Once you've updated the project's build settings, make sure to clean the project first before re-running. Let us know if this works for you!

I am closing this issue for now but feel free to re-open it if required.

**Closed by ami-aman** 2022-10-13 10:02 UTC
