### ISSUE TITLE
iOS compile failed due to error UnhandledPromiseRejection in 3.6.0

### ISSUE THREAD

**Issue by Bob-MYMC** [customerio/customerio-reactnative#256] opened 2024-04-14 22:12 UTC
**SDK version:** 3.6.0

**Environment:** Development and Production

**Are logs available?**

node:internal/process/promises:288
            triggerUncaughtException(err, true /\* fromPromise \*/);
            ^

\[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening meka.xcworkspace.".\] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Describe the bug**

After upgrade to 3.6.0, the iOS compile shows the error as above,
I works with version is 3.5.2

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/e4d975d4-316c-444b-8455-7808b794558c/d7807476-1cb4-4909-b642-da5d70a749e8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy9lNGQ5NzVkNC0zMTZjLTQ0NGItODQ1NS03ODA4Yjc5NDU1OGMvZDc4MDc0NzYtMWNiNC00OTA5LWI2NDItZGE1ZDcwYTc0OWU4IiwiaWF0IjoxNzEzMjc5ODE3LCJleHAiOjMzMjgzODM5ODE3fQ.YklgLdu5mlI1p9h2vlbJGHCG9Tt6QEWaMmmC16vh4uo "=1903x")

**Additional context**

after removing the change on file `project.pbxproj`, the project can be compiled.

![image](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/6b3b49fa-4f92-4e7f-8412-5ba419fb07f8/a19b8423-d479-4375-9093-b4e45c2659ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy82YjNiNDlmYS00ZjkyLTRlN2YtODQxMi01YmE0MTlmYjA3ZjgvYTE5Yjg0MjMtZDQ3OS00Mzc1LTkwOTMtYjRlNDVjMjY1OWNlIiwiaWF0IjoxNzEzMjc5ODE3LCJleHAiOjMzMjgzODM5ODE3fQ.iF7C_fUVa39pLnaDyaKlkgoj6mvj_nimFb9NmUz41EQ "=1532x")

**Comment by levibostian** [comment] 2024-04-15 16:48
Hey there. Sorry to hear that you encountered this issue. 

From looking over everything that you have sent, this appears to me to be a cocoapods behavior and not a behavior caused by the Customer.io SDK. I believe that cocoapods made this modification to your `project.pbxproj` file that has caused this issue. 

I am glad to hear that you are able to compile your project again after removing the change made to `project.pbxproj`. Because you are able to continue compiling your app, is there anything else I can help you with on this issue? 

If you continue to encounter this problem and are able to provide a series of steps to reproduce this issue, feel free to send those steps over to us and we can dig into this deeper for you. 

Have a great day!

**Comment by levibostian** [comment] 2024-04-16 14:36
That is helpful, thank you. The `project.pbxproj` may be modified because our latest version of the React Native SDK adds privacy manifest resource files. The diff screenshot in the description doesn't include any paths related to the SDK but the screenshots in your last comment does show paths related to these new resource files. 

Could you try building your app with Xcode, by opening meka.xcworkspace and performing a build? If you get any errors, send them in a comment. Please be sure to include the entire error message. Sometimes screenshots in Xcode do not include the entire error message.

**Comment by Bob-MYMC** [comment] 2024-04-16 14:55
Here is the error from Xcode:

<img width="1277" alt="image" src="https://github.com/customerio/customerio-reactnative/assets/63215251/c8a36912-5150-4932-a53d-c72fe1f444b7">


[Build meka_2024-04-17T00-50-36.txt](https://github.com/customerio/customerio-reactnative/files/14998771/Build.meka_2024-04-17T00-50-36.txt)

**Comment by levibostian** [comment] 2024-04-16 15:34
That error log is very helpful, thank you. 

It looks a file permission issue for macOS. `/usr/bin/sandbox-exec` is trying to execute a script and that script is trying to write a new file to your Desktop but it does not have permission to do so. 

I have personally not seen this error before but I wonder if this is caused by macOS restricting apps from writing files to your Desktop by default. If you move your codebase into a different folder (I personally use `~/code/`) on your computer or you give file system permissions to Xcode, that may solve your issue.

**Comment by Bob-MYMC** [comment] 2024-04-16 23:29
@levibostian  Thanks for your suggestions.
It finally works by this solution: [https://stackoverflow.com/questions/76792138/sandbox-bash72986-deny1-file-write-data-users-xxx-ios-pods-resources-to-co](url)

`update your Xcode project build option 'ENABLE_USER_SCRIPT_SANDBOXING' to 'No'.`
![image](https://github.com/customerio/customerio-reactnative/assets/63215251/ff37528f-aecc-4325-afab-123fa27bf621)

**Comment by levibostian** [comment] 2024-04-17 12:24
Glad to hear that you found a solution! 

I'll close this issue since you have it working. Feel free to open new issues in the future. Have a great day!

**Closed by levibostian** 2024-04-17 12:24 UTC
