### ISSUE TITLE
Deep links not working when opening the app from killed state [iOS + FCM]

### ISSUE THREAD

**Issue by ninjz** [customerio/customerio-reactnative#47] opened 2022-11-16 04:10 UTC
**SDK version:** 1.0.0

**Environment:** Development

**Are logs available?**  N/A

**Describe the bug**

I am using FCM for push notifications on iOS and am looking to set up deep linking through Push. Also using react-navigation to handle navigation in the app and in turn for deep links.

So far I am able to successfully navigate to the expected route after tapping on the notification when the app is backgrounded/foregrounded. However, when tapping the notification while the app has been killed it does not navigate with the deep link.

The docs also miss a critical piece of code that left without the deep linking does not work at all:
```objc
// Add inside AppDelegate.m making sure to also set the AppDelegate as the delegate for UNUserNotificationCenter
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

I had to dig in to the iOS SDK and piece together instructions to make this work on my app with FCM. Not sure if this works properly with the APNS implementation however I don't want to have to redo this entire implementation.

I'm handling  `public func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {` using the handler within `CioMessagingPushFCM` I wonder if the that package has not been tested fully and in parity with the APNS counterpart?

Also, tried logging the output of `Linking.getInitialUrl()` and it always returns null.

Is this a known issue? And if so, how should I get around this and get deep links functioning when the app is in the killed state on iOS (react native) via FCM?

**To Reproduce**

1. Setup deep linking on iOS via FCM; alert output of `Linking.getInitialUrl()`
3. Install app
4. Kill the app
5. Send a push notification with embedded deep link
6. Tap on push notification
7. Should see that the alert should return null

**Expected behavior**

Tapping on a push notification with a deep link should result in `Linking.getInitialUrl()` returning the deep link url. With that expected output react-navigation should route to the correct route.

**Comment by ami-aman** [comment] 2022-11-16 14:35
Hi @ninjz 
Thanks for bringing this to our notice.
I am investigating this issue and could reproduce it on my end as well. I will get back to you with a solution soon.

**Comment by ami-aman** [comment] 2022-11-21 17:44
Hi @ninjz  
Thank you for your patience. 

Our team investigated on this issue and found that it could be because of the following reasons :

- If the app is has Debugging enabled
- When react native lifecycle starts after the user taps on push notification

Make sure you are NOT running the app with Debugging enabled. In case it is already off and you still you do not see deep link working as expected then you may try this workaround. I say work around because the native tap event gets fired before the React native app lifecycle starts which causes the app to miss the received event (push notification deep link).

1. Send some custom data in payload with the deep-link. Example below with new field **react-deep-link**
```
{
    "CIO": {
        "push": {
            "image": "https://thumbs.dreamstime.com/b/bee-flower-27533578.jpg",
            "link": "amiapp://showtrial"
        }
    },
    "react-deep-link":"amiapp://showtrial",
    "aps": {
        "mutable-content": 1,
        "sound": "default",
        "alert": {
            "title": "Voila! You just logged in as a user",
            "sound": "default",
            "body": "Thanks for using the app."
        }
    }
}
```

2. Update AppDelegate.m 's **didFinishLaunchingWithOptions** method :

```
NSMutableDictionary *modifiedLaunchOptions = [NSMutableDictionary dictionaryWithDictionary:launchOptions];
  if (launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey]) {
      NSDictionary *pushContent = launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey];
      if (pushContent[@"react-deep-link"]) {
          NSString *initialURL = pushContent[@"react-deep-link"];
          if (!launchOptions[UIApplicationLaunchOptionsURLKey]) {
              modifiedLaunchOptions[UIApplicationLaunchOptionsURLKey] = [NSURL URLWithString:initialURL];
          }
      }
  }

 RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions: modifiedLaunchOptions];
```
Note that in the last line i.e. on creating a bridge, you are now supposed to send the **modifiedLaunchOptions** !

Also, I so much appreciate you for letting me know that we are missing some important steps in our docs wrt deep linking. I am working on it to fix it as soon as possible. And, do let me know if this works for you.

I am closing the ticket for now, but feel free to open it in case this doesn't help.

**Closed by ami-aman** 2022-11-21 17:44 UTC
