### ISSUE TITLE
No such module 'CioMessagingPushFCM'

### ISSUE THREAD

**Issue by isavega-neat** [customerio/customerio-reactnative#360] opened 2024-11-18 20:58 UTC
**SDK version:** customerio-reactnative": "4.1.0"

**Are logs available?** 
Logs available in the screenshot

**Describe the issue**
The 'CioMessagingPushFCM' pod is not recognized in the import of the MyAppPushNotificationsHandler.swift file (as suggested in the documentation).

The podfile is correctly configured and the pods were installed successfully.

**Screenshots**
<img width="594" alt="image" src="https://github.com/user-attachments/assets/aedffe24-9743-4520-b9fc-7b9ffb54837a">
<img width="248" alt="image" src="https://github.com/user-attachments/assets/a1a8a9f4-bb16-4619-8ec8-253ce2dba521">

**Additional context**
Integration of push notifications based on FCM and Objective-C. The documentation is not quite clear, please review.

**Comment by isavega-neat** [comment] 2024-11-19 13:04
Thank you very much for your prompt reply, I will give you more details: 

1. Yes, MyAppPushNotificationsHandler has been added to the main target.
 
2. Here goes my Podfile: 


```
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'
prepare_react_native_project!

def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyApp' do
  use_expo_modules!

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  pod "react-native-heap", path: "../node_modules/@heap/react-native-heap"

  # Flags change depending on the env values.
  flags = get_default_flags()

  # Pods required by Customer.io
  pod 'customerio-reactnative/fcm', :path => '../node_modules/customerio-reactnative'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'Camera',             
    'Notifications',        
    'FaceID',               
  ])

  # target 'MyAppTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../.env.development',
    'Release' => '$(PODS_ROOT)/../../.env.production',
  }

  post_install do |installer|
    react_native_post_install(
      installer,

      :mac_catalyst_enabled => false
    )
  
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
  
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
  
        if target.name == "React-Codegen"
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        end
  
    
        if target.name == 'BoringSSL-GRPC'
          target.source_build_phase.files.each do |file|
            if file.settings && file.settings['COMPILER_FLAGS']
              flags = file.settings['COMPILER_FLAGS'].split
              flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
              file.settings['COMPILER_FLAGS'] = flags.join(' ')
            end
          end
        end
      end
    end
  end
end

target 'NotificationServiceExtension' do
  use_frameworks! :linkage => :static
  pod 'customerio-reactnative-richpush/fcm', :path => '../node_modules/customerio-reactnative'
  pod "FirebaseMessaging"
end
```


3. I followed the FCM/Objective-C documentation step by step, there are confusing steps, for example:

      a) Step 3 of the documentation says to configure MyAppPushNotificationsHandler.swift with the siteId and apiKey but none of these variables appear in the proposed code. 
      b) Step 9 of the documentation talks about creating a NotificationServiceExtension.m file when the target creates a .Swift file. Also, the example code shows a NotificationService.m file. Which is extremely confusing. It also does not talk about the need to set up a bridge if Swift and Objective-C files are used. 

Thanks for clarifying my questions! 🙏

**Comment by mrehan27** [comment] 2024-11-19 14:01
Thank you for the detailed response @isavega-neat. This is really helpful. Appreciate the thorough explanation.  

Your `Podfile` looks correct. Can you please try the following steps:  

- Remove all cached versions and project build folders
- Reinstall all React Native dependencies
- Run `pod install` again to ensure the dependencies are fetched properly

If the issue persists, please drop us an email at win@customer.io with following details so we can help you better:

- `Podfile` and `Podfile.lock`
- Files showing errors during the build (e.g., `MyAppPushNotificationsHandler`) or any other files with errors
- Complete `pod install` logs, build logs, and the full error message
- Any additional details you think might help us
- A link to this GitHub ticket for reference

Regarding your documentation feedback, you're absolutely right. The summary is outdated, as we now only require `cdpApiKey`. Thanks for pointing that out, we'll update it soon.  

Thank you for your patience and understanding!

**Comment by isavega-neat** [comment] 2024-11-19 14:51
Ok, I will write you an email with the details! 

Thanks for the support, best regards

**Comment by mrehan27** [comment] 2024-11-21 19:21
Closing this for now. We'll continue helping through support once requested details are shared via email. Even though the issue is closed, please feel free to reach out with any additional questions you may have.

**Closed** 2024-11-21 19:21 UTC
